"""Tests electric.meter.component.gt type, version 000"""

from gwproto.data_classes.components import ElectricMeterComponent
from gwproto.types import ElectricMeterComponentGt
from tests.component_load_utils import ComponentCase, assert_component_load


def test_electric_meter_component_gt_generated() -> None:
    d = {
        "ComponentAttributeClassId": "739a6e32-bb9c-43bc-a28d-fb61be665522",
        "ComponentId": "dce5c63d-8a38-439e-88ac-dd5ad845e9ca",
        "ConfigList": [
            {
                "AsyncCapture": True,
                "AsyncCaptureDelta": 200,
                "CapturePeriodS": 300,
                "ChannelName": "hp-odu-pwr",
                "Exponent": 0,
                "PollPeriodMs": 1000,
                "EgaugeRegisterConfig": {
                    "Address": 9006,
                    "Denominator": 1,
                    "Description": "change in value",
                    "Name": "",
                    "Type": "f32",
                    "TypeName": "egauge.register.config",
                    "Unit": "W",
                    "Version": "000",
                },
                "TypeName": "electric.meter.channel.config",
                "Unit": "W",
                "Version": "000",
            },
            {
                "AsyncCapture": True,
                "AsyncCaptureDelta": 50,
                "CapturePeriodS": 300,
                "ChannelName": "hp-idu-pwr",
                "Exponent": 0,
                "PollPeriodMs": 1000,
                "EgaugeRegisterConfig": {
                    "Address": 9000,
                    "Denominator": 1,
                    "Description": "change in value",
                    "Name": "",
                    "Type": "f32",
                    "TypeName": "egauge.register.config",
                    "Unit": "W",
                    "Version": "000",
                },
                "TypeName": "electric.meter.channel.config",
                "Unit": "W",
                "Version": "000",
            },
            {
                "AsyncCapture": True,
                "AsyncCaptureDelta": 10,
                "CapturePeriodS": 300,
                "ChannelName": "primary-pump-pwr",
                "Exponent": 0,
                "PollPeriodMs": 1000,
                "EgaugeRegisterConfig": {
                    "Address": 9012,
                    "Denominator": 1,
                    "Description": "change in value",
                    "Name": "",
                    "Type": "f32",
                    "TypeName": "egauge.register.config",
                    "Unit": "W",
                    "Version": "000",
                },
                "TypeName": "electric.meter.channel.config",
                "Unit": "W",
                "Version": "000",
            },
            {
                "AsyncCapture": True,
                "AsyncCaptureDelta": 10,
                "CapturePeriodS": 300,
                "ChannelName": "dist-pump-pwr",
                "Exponent": 0,
                "PollPeriodMs": 1000,
                "EgaugeRegisterConfig": {
                    "Address": 9010,
                    "Denominator": 1,
                    "Description": "change in value",
                    "Name": "",
                    "Type": "f32",
                    "TypeName": "egauge.register.config",
                    "Unit": "W",
                    "Version": "000",
                },
                "TypeName": "electric.meter.channel.config",
                "Unit": "W",
                "Version": "000",
            },
            {
                "AsyncCapture": True,
                "AsyncCaptureDelta": 10,
                "CapturePeriodS": 300,
                "ChannelName": "store-pump-pwr",
                "Exponent": 0,
                "PollPeriodMs": 1000,
                "EgaugeRegisterConfig": {
                    "Address": 9014,
                    "Denominator": 1,
                    "Description": "change in value",
                    "Name": "",
                    "Type": "f32",
                    "TypeName": "egauge.register.config",
                    "Unit": "W",
                    "Version": "000",
                },
                "TypeName": "electric.meter.channel.config",
                "Unit": "W",
                "Version": "000",
            },
            {
                "AsyncCapture": True,
                "AsyncCaptureDelta": 10,
                "CapturePeriodS": 300,
                "ChannelName": "oil-boiler-pwr",
                "Exponent": 0,
                "PollPeriodMs": 1000,
                "EgaugeRegisterConfig": {
                    "Address": 9016,
                    "Denominator": 1,
                    "Description": "change in value",
                    "Name": "",
                    "Type": "f32",
                    "TypeName": "egauge.register.config",
                    "Unit": "W",
                    "Version": "000",
                },
                "TypeName": "electric.meter.channel.config",
                "Unit": "W",
                "Version": "000",
            },
        ],
        "DisplayName": "eGauge6069.local",
        "HwUid": "BP01349",
        "ModbusHost": "eGauge6069.local",
        "ModbusPort": 502,
        "TypeName": "electric.meter.component.gt",
        "Version": "001",
    }
    assert_component_load(
        [
            ComponentCase(
                "ElectricMeterComponentGt",
                d,
                ElectricMeterComponentGt,
                ElectricMeterComponent,
            )
        ]
    )
